#-*- coding: utf-8 -*-

{
	"name": "Vit Contract",
	"version": "1.0",
	"depends": [
		"base",
	],
	"author": "Akhmad Daniel Sembiring",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": [
		"static/description/images/main_screenshot.jpg"
	],
	"price": "100",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "",
	"description": "",
	"data": [
		"security/groups.xml",
		"security/ir.model.access.csv",
		"view/menu.xml",
		"view/izin_prinsip.xml",
		"report/izin_prinsip.xml",
		"data/sequence_izin_prinsip.xml",
		"view/budget_rkap.xml",
		"report/budget_rkap.xml",
		"view/kanwil_kancab.xml",
		"report/kanwil_kancab.xml",
		"view/kontrak.xml",
		"report/kontrak.xml",
		"data/sequence_kontrak.xml",
		"view/partner.xml",
		"view/payment.xml",
		"report/payment.xml",
		"data/sequence_payment.xml",
		"view/syarat_termin.xml",
		"report/syarat_termin.xml",
		"view/kontrak_state.xml",
		"report/kontrak_state.xml",
		"data/vit.kontrak_state.csv",
		"view/termin.xml",
		"report/termin.xml",
		"data/sequence_termin.xml",
		"view/izin_prinsip_line.xml",
		"report/izin_prinsip_line.xml",
		"view/master_syarat_termin.xml",
		"report/master_syarat_termin.xml",
		"view/jenis_kontrak.xml",
		"report/jenis_kontrak.xml",
		"view/master_nama_termin.xml",
		"report/master_nama_termin.xml",
		"view/state_payment.xml",
		"report/state_payment.xml",
		"data/vit.state_payment.csv",
		"view/state_izin_prinsip.xml",
		"report/state_izin_prinsip.xml",
		"data/vit.state_izin_prinsip.csv",
		"view/master_budget.xml",
		"report/master_budget.xml",
		"view/droping.xml",
		"report/droping.xml",
		"data/sequence_droping.xml",
		"view/state_termin.xml",
		"report/state_termin.xml",
		"data/vit.state_termin.csv",
		"view/state_droping.xml",
		"report/state_droping.xml",
		"data/vit.state_droping.csv"
	],
	"installable": True,
	"auto_install": False,
	"application": True,
	"odooVersion": 17
}